name: "Gatsby Publish"
description: "Build and deploy your Gatsby site to GitHub Pages."
branding:
  icon: "book-open"
  color: "purple"
inputs:
  access-token:
    description: "A personal access token needed to push your site after it has been built."
    required: false
  deploy-branch:
    description: "The branch expected by GitHub to have the static files needed for your site."
    required: false
    default: "master"
  deploy-repo:
    description: "The repo expected by GitHub to have the static files needed for your site."
    required: false
    default: ""
  gatsby-args:
    description: "Additional arguments that get passed to `gatsby build`."
    required: false
    default: ""
  skip-publish:
    description: "Builds your Gatsby site but skips publishing by setting it to `true`. Helpful for testing/debugging Workflows."
    required: false
    default: false
  working-dir:
    description: "The directory where your Gatsby source files are at. `gatsby build` will run from this directory."
    required: false
    default: "."
  commit-message:
    description: "The commit message used for pushing changes to the deploy branch."
    required: false
    default: ""
  git-config-name:
    description: "The name under which the deploy commit is pushed to the deploy branch."
    required: false
    default: ""
  git-config-email:
    description: "The email adress under which the deploy commit is pushed to the deploy branch."
    required: false
    default: ""
runs:
  using: "node16"
  main: "./dist/index.js"
