name: "Gatsby Publish"
description: "Build and deploy your Gatsby site to GitHub Pages."
branding:
  icon: "book-open"
  color: "purple"
inputs:
  access-token:
    description: "A personal access token needed to push your site after it has been built."
    required: false
  deploy-branch:
    description: "The branch expected by GitHub to have the static files needed for your site."
    required: false
    default: "gh-pages"
  deploy-repo:
    description: "The repo expected by GitHub to have the static files needed for your site."
    required: false
    default: ""
  gatsby-args:
    description: "Additional arguments that get passed to `gatsby build`."
    required: false
    default: ""
  skip-publish:
    description: "Skips publishing - performs build/test"
    required: false
    default: false
runs:
  using: "node12"
  main: "index.js"
